version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile.client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: ../Dockerfile.server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/medimitra
      - ML_SERVER_URL=http://ml-server:8000
      - RASA_SERVER_URL=http://chatbot:5005
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - mongo
      - ml-server
  ml-server:
    build:
      context: ./ml-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
